global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'email-optimizer'
    environment: 'production'

scrape_configs:
  - job_name: 'email-optimizer'
    static_configs:
      - targets: ['app:8000']
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 5s